use std::time::Instant;

/// `Agent` objects represent registered clients connecting to this server instance. Each registered
/// `Agent` must have a unique `agent_id` (generated by the server) and an `app` type associated with it.
pub struct Agent {
    pub agent_id: String,
    pub hostname: Option<String>,
    pub app: String,
    pub registration_time: Instant
}
