[package]
name = "squiddy-agent"
version = "0.1.0"
authors = ["Alex Pecsi <alex.pecsi@gmail.com>"]

[dependencies]
squiddy-proto = { path = "../squiddy-proto" }
bytes = "*"
native-tls = "0.1.*"
serde = "1.0.*"
serde_derive = "1.0.*"
toml = "*"
