[package]
name = "squiddy-server"
version = "0.1.0"
authors = ["Alex Pecsi <alex.pecsi@gmail.com>"]

[dependencies]
native-tls = "0.1.5"
futures = "*"
tokio = "0.1.*"
bytes = "*"

[target.'cfg(unix)'.dependencies]
termion = "1"
